# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
pipelineId: "pipeline-dataproc-ephemeral-relative-resource-profile-pyspark"
description: "A pipeline with a Dataproc Ephemeral cluster running the PySpark task."
runner: "airflow"
owner: "data-eng-team"
tags: ["dataproc_create_batch", "example"]
modelVersion: "1.0"

defaults:
  projectId: "your-gcp-project-id"
  location: "us-central1"
  executionConfig:
    retries: 0

triggers:
  - schedule:
      interval: "0 5 * * *"
      startTime: "2025-10-01T00:00:00"
      endTime: "2026-10-01T00:00:00"
      catchup: false
      timezone: "UTC"

actions:
  - pyspark:
      name: "run_dataproc_ephemeral"
      executionTimeout: "1h"
      mainFilePath: "./scripts/my_spark_job.py"
      engine:
        dataprocOnGce:
          ephemeralCluster:
            projectId: "your-gcp-project-id"
            location: "us-central1"
            clusterName: "ephemeral-cluster-relative-path"
            resourceProfile:
              path: "resource-profile/cluster-config-resource-profile.yml"
            properties:
              spark.submit.deployMode: "cluster"
              spark.yarn.appMasterEnv.PYTHONPATH: "./libs/lib/python3.11/site-packages"
              spark.executorEnv.PYTHONPATH: "./libs/lib/python3.11/site-packages"
